From events to EventTarget
jessetane/queue pull request #92
Opened 2023-02-11 12:01 UTC by MaksimLavrenyuk

2023-02-13 18:39 UTC, jessetane requested changes
looking good! only thought is that the detail property for error should literally be `error` instead of `err`

2023-02-13 19:13 UTC, MaksimLavrenyuk commented on index.js
> +          this.dispatchEvent(new QueueEvent('error', { err, job }))
Yeah, sure.

2023-02-13 19:19 UTC, jessetane commented
thanks. so this is where i would use `git rebase -i` to squash these new commits with their earlier counterparts so the history stays clean. not trying to be annoying but i think most open source projects will expect this in the PR feedback / iteration process. if it's too much hassle though i can live with it as is

2023-02-13 19:20 UTC, jessetane commented
haven't read this but it came up with a quick search, maybe helpful: https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history#interactive-rebase

2023-02-13 19:29 UTC, MaksimLavrenyuk commented
Thanks for the tip! Yeah, I'll do it https://github.com/jessetane/queue/pull/92#issuecomment-1428520093, it's time for me to figure it out.

2023-02-13 19:32 UTC, jessetane commented
note that when you alter history you'll have to force push to your branch, but this is normal

2023-02-13 19:52 UTC, MaksimLavrenyuk commented
@jessetane

Check this

2023-02-13 20:03 UTC, merged

2023-02-13 20:04 UTC, jessetane commented
what's next?

2023-02-13 20:08 UTC, MaksimLavrenyuk commented
We need to switch to Promise instead of callback. After that I would like to add a d.ts file to support projects that use typescript.

2023-02-13 20:13 UTC, jessetane commented
sounds good, let's tackle those in separate PR's. ideally we can continue to support promises _and_ callbacks, but maybe take into account concerns raised in #85 and #34?

2023-02-26 18:36 UTC, MaksimLavrenyuk commented
@jessetane 

I apologize for the delay, my main work takes a lot of time.

For issue https://github.com/jessetane/queue/issues/34, I created a [PR](https://github.com/jessetane/queue/pull/93).
For issue https://github.com/jessetane/queue/issues/85, there are questions that need to be discussed. I will write to the issue itself.